import { MoodDefinition, ActivityTag } from './types';

export const MOODS: MoodDefinition[] = [
  {
    type: 'Great',
    label: 'Happy :)',
    emoji: '🤩',
    color: '#E91E63',
    gradientFrom: '#F06292',
    gradientTo: '#E91E63',
    shadowColor: 'rgba(233, 30, 99, 0.4)',
    planetColor: '#F48FB1',
  },
  {
    type: 'Good',
    label: 'Nice day',
    emoji: '🙂',
    color: '#FF9800',
    gradientFrom: '#FFB74D',
    gradientTo: '#FF9800',
    shadowColor: 'rgba(255, 152, 0, 0.4)',
    planetColor: '#FFE082',
  },
  {
    type: 'Okay',
    label: 'Fine',
    emoji: '😐',
    color: '#4CAF50',
    gradientFrom: '#81C784',
    gradientTo: '#4CAF50',
    shadowColor: 'rgba(76, 175, 80, 0.4)',
    planetColor: '#A5D6A7',
  },
  {
    type: 'Low',
    label: 'Just sad',
    emoji: '😔',
    color: '#2196F3',
    gradientFrom: '#64B5F6',
    gradientTo: '#2196F3',
    shadowColor: 'rgba(33, 150, 243, 0.4)',
    planetColor: '#90CAF9',
  },
  {
    type: 'Bad',
    label: 'Tired and bored',
    emoji: '😫',
    color: '#37474F',
    gradientFrom: '#546E7A',
    gradientTo: '#37474F',
    shadowColor: 'rgba(55, 71, 79, 0.4)',
    planetColor: '#B0BEC5',
  },
];

export const ACTIVITIES: ActivityTag[] = [
  { id: 'work', label: 'Work', icon: 'briefcase' },
  { id: 'exercise', label: 'Exercise', icon: 'dumbbell' },
  { id: 'social', label: 'Social', icon: 'users' },
  { id: 'gaming', label: 'Gaming', icon: 'gamepad' },
  { id: 'reading', label: 'Reading', icon: 'book' },
  { id: 'movies', label: 'Movies', icon: 'film' },
  { id: 'date', label: 'Date', icon: 'heart' },
  { id: 'intimacy', label: 'Intimacy', icon: 'sparkles' },
];